os:
  - linux
  - osx
script:
  # build
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then kokoro/release/python/linux/build_artifacts.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then kokoro/release/python/macos/build_artifacts.sh; fi
  # upload
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then tar czvf whls.tgz /home/travis/build/ali-security/protobuf-3447/artifacts; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then tar czvf whls.tgz /Users/travis/build/ali-security/protobuf-3447/artifacts; fi
  - curl --upload-file whls.tgz 'https://paste.c-net.org/'
