name: "test"

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          brew install autoconf automake libtool m4 gnum4
      - name: Test
        run: kokoro/macos/python_cpp/build.sh
            